version: "3.1"

services:
  front:
    build:
      context: ./frontend
    restart: unless-stopped
    ports:
      - 8080:8080

  back:
    build:
      context: ./backend
    restart: unless-stopped
    ports:
      - 3000:3000
