version: "3.1"

services:
  mongodb:
    container_name: mongodb
    image: mongo
    ports:
      - "27017:27017"

  front:
    build:
      context: ./frontend
    restart: unless-stopped
    ports:
      - 8080:8080
    volumes:
      - ./frontend:/usr/src/app/frontend
      
  back:
    build:
      context: ./backend
    restart: unless-stopped
    ports:
      - 3000:3000
    links:
      - mongodb
    volumes:
      - ./backend:/usr/src/app/backend

  chrome:
    image: selenium/standalone-chrome
    volumes:
      - /dev/shm:/dev/shm
    ports:
      - "4444:4444"
